/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MembersRouteImport } from './routes/members'
import { Route as RegisteredUsersRouteImport } from './routes/registered-users'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as UsersRouteImport } from './routes/users'
import { Route as VisitorsRouteImport } from './routes/visitors'
import { Route as MembersIndexRouteImport } from './routes/members.index'
import { Route as MembersIdRouteImport } from './routes/members.$id'
import { Route as RegisteredUsersIndexRouteImport } from './routes/registered-users.index'
import { Route as RegisteredUsersIdRouteImport } from './routes/registered-users.$id'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as UsersIdRouteImport } from './routes/users.$id'
import { Route as VisitorsIndexRouteImport } from './routes/visitors.index'
import { Route as VisitorsIdRouteImport } from './routes/visitors.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisteredUsersRoute = RegisteredUsersRouteImport.update({
  id: '/registered-users',
  path: '/registered-users',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitorsRoute = VisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MembersRoute,
} as any)
const MembersIdRoute = MembersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MembersRoute,
} as any)
const RegisteredUsersIndexRoute = RegisteredUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegisteredUsersRoute,
} as any)
const RegisteredUsersIdRoute = RegisteredUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RegisteredUsersRoute,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UsersRoute,
} as any)
const VisitorsIndexRoute = VisitorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VisitorsRoute,
} as any)
const VisitorsIdRoute = VisitorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VisitorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRouteWithChildren
  '/registered-users': typeof RegisteredUsersRouteWithChildren
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRouteWithChildren
  '/visitors': typeof VisitorsRouteWithChildren
  '/members/$id': typeof MembersIdRoute
  '/registered-users/$id': typeof RegisteredUsersIdRoute
  '/users/$id': typeof UsersIdRoute
  '/visitors/$id': typeof VisitorsIdRoute
  '/members/': typeof MembersIndexRoute
  '/registered-users/': typeof RegisteredUsersIndexRoute
  '/users/': typeof UsersIndexRoute
  '/visitors/': typeof VisitorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/members/$id': typeof MembersIdRoute
  '/registered-users/$id': typeof RegisteredUsersIdRoute
  '/users/$id': typeof UsersIdRoute
  '/visitors/$id': typeof VisitorsIdRoute
  '/members': typeof MembersIndexRoute
  '/registered-users': typeof RegisteredUsersIndexRoute
  '/users': typeof UsersIndexRoute
  '/visitors': typeof VisitorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRouteWithChildren
  '/registered-users': typeof RegisteredUsersRouteWithChildren
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRouteWithChildren
  '/visitors': typeof VisitorsRouteWithChildren
  '/members/$id': typeof MembersIdRoute
  '/registered-users/$id': typeof RegisteredUsersIdRoute
  '/users/$id': typeof UsersIdRoute
  '/visitors/$id': typeof VisitorsIdRoute
  '/members/': typeof MembersIndexRoute
  '/registered-users/': typeof RegisteredUsersIndexRoute
  '/users/': typeof UsersIndexRoute
  '/visitors/': typeof VisitorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/members'
    | '/registered-users'
    | '/reports'
    | '/users'
    | '/visitors'
    | '/members/$id'
    | '/registered-users/$id'
    | '/users/$id'
    | '/visitors/$id'
    | '/members/'
    | '/registered-users/'
    | '/users/'
    | '/visitors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reports'
    | '/members/$id'
    | '/registered-users/$id'
    | '/users/$id'
    | '/visitors/$id'
    | '/members'
    | '/registered-users'
    | '/users'
    | '/visitors'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/members'
    | '/registered-users'
    | '/reports'
    | '/users'
    | '/visitors'
    | '/members/$id'
    | '/registered-users/$id'
    | '/users/$id'
    | '/visitors/$id'
    | '/members/'
    | '/registered-users/'
    | '/users/'
    | '/visitors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRouteWithChildren
  RegisteredUsersRoute: typeof RegisteredUsersRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  UsersRoute: typeof UsersRouteWithChildren
  VisitorsRoute: typeof VisitorsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registered-users': {
      id: '/registered-users'
      path: '/registered-users'
      fullPath: '/registered-users'
      preLoaderRoute: typeof RegisteredUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visitors': {
      id: '/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof VisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof MembersRoute
    }
    '/members/$id': {
      id: '/members/$id'
      path: '/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof MembersIdRouteImport
      parentRoute: typeof MembersRoute
    }
    '/registered-users/': {
      id: '/registered-users/'
      path: '/'
      fullPath: '/registered-users/'
      preLoaderRoute: typeof RegisteredUsersIndexRouteImport
      parentRoute: typeof RegisteredUsersRoute
    }
    '/registered-users/$id': {
      id: '/registered-users/$id'
      path: '/$id'
      fullPath: '/registered-users/$id'
      preLoaderRoute: typeof RegisteredUsersIdRouteImport
      parentRoute: typeof RegisteredUsersRoute
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRoute
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof UsersRoute
    }
    '/visitors/': {
      id: '/visitors/'
      path: '/'
      fullPath: '/visitors/'
      preLoaderRoute: typeof VisitorsIndexRouteImport
      parentRoute: typeof VisitorsRoute
    }
    '/visitors/$id': {
      id: '/visitors/$id'
      path: '/$id'
      fullPath: '/visitors/$id'
      preLoaderRoute: typeof VisitorsIdRouteImport
      parentRoute: typeof VisitorsRoute
    }
  }
}

interface MembersRouteChildren {
  MembersIdRoute: typeof MembersIdRoute
  MembersIndexRoute: typeof MembersIndexRoute
}

const MembersRouteChildren: MembersRouteChildren = {
  MembersIdRoute: MembersIdRoute,
  MembersIndexRoute: MembersIndexRoute,
}

const MembersRouteWithChildren =
  MembersRoute._addFileChildren(MembersRouteChildren)

interface RegisteredUsersRouteChildren {
  RegisteredUsersIdRoute: typeof RegisteredUsersIdRoute
  RegisteredUsersIndexRoute: typeof RegisteredUsersIndexRoute
}

const RegisteredUsersRouteChildren: RegisteredUsersRouteChildren = {
  RegisteredUsersIdRoute: RegisteredUsersIdRoute,
  RegisteredUsersIndexRoute: RegisteredUsersIndexRoute,
}

const RegisteredUsersRouteWithChildren = RegisteredUsersRoute._addFileChildren(
  RegisteredUsersRouteChildren,
)

interface UsersRouteChildren {
  UsersIdRoute: typeof UsersIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersIdRoute: UsersIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

interface VisitorsRouteChildren {
  VisitorsIdRoute: typeof VisitorsIdRoute
  VisitorsIndexRoute: typeof VisitorsIndexRoute
}

const VisitorsRouteChildren: VisitorsRouteChildren = {
  VisitorsIdRoute: VisitorsIdRoute,
  VisitorsIndexRoute: VisitorsIndexRoute,
}

const VisitorsRouteWithChildren = VisitorsRoute._addFileChildren(
  VisitorsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRouteWithChildren,
  RegisteredUsersRoute: RegisteredUsersRouteWithChildren,
  ReportsRoute: ReportsRoute,
  UsersRoute: UsersRouteWithChildren,
  VisitorsRoute: VisitorsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
